name: Feature Request
description: Request a new feature
title: "[Feature] "
labels: ["type: feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Core
        - Visuals
        - Audio
        - UI
        - Gameplay
        - Performance
        - Infrastructure
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want to add?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
